node {
  stage('SonarQube analysis') {
    // requires SonarQube Scanner 2.8+
    def scannerHome = tool 'LocalSonarQubeScanner';
    bat 'echo scannerHome'
    withSonarQubeEnv('sonar_server') {
     bat "${scannerHome}/bin/sonar-scanner"
    }
  }
}
